### PR TITLE
[#249] fix URLHelper.combine if absolute URLs are used

### LINKED ISSUE #249: FileFetcher must not concatentate files if absolute URLs are used
Failed to fetch file http://foo.com/landscape/nginx/https://bar.com/v2-beta/

```
5.9.2020 05:20:35java.lang.RuntimeException: Got 404 while reading
5.9.2020 05:20:35	at de.bonndan.nivio.input.http.HttpService.executeRequest(HttpService.java:74) ~[classes!/:0.3.0]
5.9.2020 05:20:35	at de.bonndan.nivio.input.http.HttpService.get(HttpService.java:24) ~[classes!/:0.3.0]
5.9.2020 05:20:35	at de.bonndan.nivio.input.FileFetcher.get(FileFetcher.java:61) ~[classes!/:0.3.0]
```

### PR DESCRIPTION
**Pull request by BilligsterUser**
closes #249

### CODE REVIEW

File: src/test/java/de/bonndan/nivio/util/URLHelperTest.java [hunk 1]
```diff
@@ -15,55 +14,100 @@
...
+    @Test
+    void test_splitQuery_badQuery() throws MalformedURLException {
+        URL url = new URL("http://192.168.99.100:8080?foo=");
+        Map<String, String> actual = URLHelper.splitQuery(url);
+        assertEquals(0, actual.size());
+    }
+
+
+    @Test
+    void test_combine() throws MalformedURLException {
```
Comment (bonndan) [inline src/test/java/de/bonndan/nivio/util/URLHelperTest.java:69]: It can sometimes be helpful to note given/when/then is the tests to enhance readability for other developers.

```java
        //given
        String root = Paths.get("").toAbsolutePath().toString();
        if (SystemUtils.IS_OS_WINDOWS) {
            root = "/" + root.replace(File.separator, "/");
        }
        URL baseUrl = new URL("file:" + root + "/src/test/resources/example/");
        String part = "./services/wordpress.yml";

        //when
        String actual = URLHelper.combine(baseUrl, part);

        //then
        String expected = "file:" + root + "/src/test/resources/example/services/wordpress.yml";

        assertEquals(expected, actual);
```

File: src/test/java/de/bonndan/nivio/util/URLHelperTest.java [hunk 2]
```diff
@@ -15,55 +14,100 @@
...
+
+        String actual = URLHelper.combine(baseUrl, part);
+
+        String expected = "file:" + root + "/src/test/resources/example/services/wordpress.yml";
+
+        assertEquals(expected, actual);
+    }
+
+    @Test
+    void test_combine_absolute_part() throws MalformedURLException {
```
Comment (bonndan) [inline src/test/java/de/bonndan/nivio/util/URLHelperTest.java:106]: 👍

**Review by bonndan — APPROVED** [review]
Good work.
