### PR TITLE
WiP: Refactor Context/API, fix changes from backend rework

### LINKED ISSUE #126: Refactor context: api calls in cotext example
- add test

### LINKED ISSUE #133: Remove group hover effect in map
The effect is annoying. Plus, groups will be clickable soon.

### LINKED ISSUE #134: Refactor map item click
- [ ] remove modal since it blocks access to the map
- [ ] show "context menu" on the right border (maybe within drawer) containing info on the node
- [ ] provide scribble with new layout
- [x] read data from the API instead of html inclusion, remove html item endpoint

### PR DESCRIPTION
**Pull request by MarvinSchoening**
Closes #133 
Closes #126
Closes #134 "read data from the API instead of html inclusion, remove html item endpoint"

Remove console :(

### CODE REVIEW

File: src/main/app/src/App.tsx [hunk 1]
```diff
@@ -5,7 +5,7 @@ import LandscapeOverview from './Components/LandscapeComponent/LandscapeOverview
 import Landscape from './Components/LandscapeComponent/Landscape/Landscape';
 import Man from './Components/ManComponent/Man';
 import Layout from './Components/LayoutComponent/Layout';
-import Events from "./Components/EventComponent/Events";
+import Events from './Components/EventComponent/Events';
```
Comment (bonndan) [inline src/main/app/src/App.tsx:8]: What is actually the difference in JS?

File: src/main/app/src/interfaces.ts [hunk 2]
```diff
@@ -1,10 +1,35 @@
...
+  groups?: object[]; // TODO: Create interface
+  lastUpdate?: string;
+  overallState?: string;
+}
+
+export interface IItem {
+  color?: string;
+  contact?: string;
+  description?: string;
+  fill?: string;
```
Comment (bonndan) [inline src/main/app/src/interfaces.ts:16]: We should think about removing the attributes width and height from the API. These are leftovers from times when to hex map was drawn in the frontend.

File: src/main/app/src/interfaces.ts [hunk 3]
```diff
@@ -1,10 +1,35 @@
...
+  height?: number;
+  icon?: string;
+  identifier: string;
+  interfaces?: Array<Object>;
+  labels?: Object;
+  lifecycle?: String;
+  links?: Object;
+  name?: String;
+  owner?: String;
+  providedBy?: Array<Object>;
```
Comment (bonndan) [inline src/main/app/src/interfaces.ts:28]: Pls check if this appears at all. ProvidedBy is a shortcut for configuring landscapes long before internal processing is done.

File: src/main/app/src/interfaces.ts [hunk 4]
```diff
@@ -1,10 +1,35 @@
...
+  lastUpdate?: string;
+  overallState?: string;
+}
+
+export interface IItem {
+  color?: string;
+  contact?: string;
+  description?: string;
+  fill?: string;
+  fullyQualifiedIdentifier?: string;
```
Comment (bonndan) [inline src/main/app/src/interfaces.ts:17]: fqi is mandatory

File: src/main/app/src/interfaces.ts [hunk 5]
```diff
@@ -1,10 +1,35 @@
...
+  group?: string;
+  height?: number;
+  icon?: string;
+  identifier: string;
+  interfaces?: Array<Object>;
+  labels?: Object;
+  lifecycle?: String;
+  links?: Object;
+  name?: String;
```
Comment (bonndan) [inline src/main/app/src/interfaces.ts:26]: name is mandatory

File: src/main/app/src/interfaces.ts [hunk 6]
```diff
@@ -1,10 +1,35 @@
...
-    items?: string[];
-    lastUpdate?: string;
+  name: string;
+  identifier: string;
+  description?: string;
+  teams?: object[]; // TODO: Create interface
+  items?: IItem[];
+  groups?: object[]; // TODO: Create interface
+  lastUpdate?: string;
+  overallState?: string;
```
Comment (bonndan) [inline src/main/app/src/interfaces.ts:9]: see LandscapeDTO, I think overallState has been removed

File: src/main/app/src/Components/LandscapeComponent/Item/LandscapeItem.tsx [hunk 7]
```diff
@@ -1,36 +1,46 @@
...
-        .then((data) => {
-          setHtml(JSON.stringify(data));
-        });
+      getItem();
     }
-  }, [element, topic, html]);
+  }, [element, topic, getItem]);
 
-  return <div className='landscapeItemContent'>{html}</div>;
+  return (
```
Comment (bonndan) [inline src/main/app/src/Components/LandscapeComponent/Item/LandscapeItem.tsx:35]: We can leave this for now. I've made a wireframe to discuss future changes.

Comment (MarvinSchoening) [reply src/main/app/src/Components/LandscapeComponent/Item/LandscapeItem.tsx:35]: no we cant because it doesnt work anymore this way, we wont get html served anymore and we cant convert json to html :/

File: src/main/app/src/App.tsx (hunk 1 above)
Comment (MarvinSchoening) [reply src/main/app/src/App.tsx:8]: its just our prettier settings, we can change it to " instead of '

File: src/main/app/src/interfaces.ts (hunk 3 above)
Comment (MarvinSchoening) [reply src/main/app/src/interfaces.ts:28]: i've added all attributes that got send within the response, idk if its used anywhere but it is send

File: src/main/app/src/interfaces.ts (hunk 6 above)
Comment (MarvinSchoening) [reply src/main/app/src/interfaces.ts:9]: yeah i wasn't sure if it was in before because we always had no data for it, i'll remove it for now

File: src/main/app/src/Components/LandscapeComponent/Item/LandscapeItem.tsx (hunk 7 above)
Comment (MarvinSchoening) [reply src/main/app/src/Components/LandscapeComponent/Item/LandscapeItem.tsx:35]: oh or do you mean styling the component? that's something that we can leave for now yes :D the slide in from the right side was the next thing i wanted to do

File: src/main/app/src/interfaces.ts (hunk 3 above)
Comment (bonndan) [reply src/main/app/src/interfaces.ts:27]: OK. Then we should #137 later.

File: src/main/app/src/interfaces.ts (hunk 2 above)
Comment (bonndan) [reply src/main/app/src/interfaces.ts:15]: see #137

**Comment by bonndan** [comment]
@MarvinSchoening From my part, you can merge this PR. Decide yourself.
