### PR TITLE
375 fix search locate

### LINKED ISSUE #375: jump-to/locate function broken after search
Clicking the focus icon in the search results does not scroll to an item's location. Maybe related to landscape change (old function still active).

### PR DESCRIPTION
**Pull request by bonndan**
closes #375

### CODE REVIEW

File: src/main/app/src/Components/Landscape/Map/Map.tsx [hunk 1]
```diff
@@ -75,7 +74,7 @@ const Map: React.FC<Props> = ({ setSidebarContent, setLocateFunction, setPageTit
         }
       }
     },
-    [value]
+    [setValue, value]
```
Comment (mfbieber) [inline src/main/app/src/Components/Landscape/Map/Map.tsx:77]: As I understood the deps of the `useCallback()` hook, these are values that change upon which the hook is triggered (https://reactjs.org/docs/hooks-reference.html#usecallback). `setValue` never changes (does it?). 

I also tested removing it, it makes no difference for the focus function.

File: src/main/app/src/Components/Landscape/Map/Map.tsx [hunk 2]
```diff
@@ -177,16 +176,19 @@ const Map: React.FC<Props> = ({ setSidebarContent, setLocateFunction, setPageTit
...
       });
     }
-  }, [identifier, setPageTitle, setLocateFunction, locateComponent, landscape]);
+  }, [identifier, setPageTitle, landscape]);
+
+  useEffect(() => {
+    if (locateComponent) {
+      setLocateFunction(() => locateComponent);
+    }
+  }, [value, setLocateFunction, locateComponent]);
```
Comment (mfbieber) [inline src/main/app/src/Components/Landscape/Map/Map.tsx:191]: Just as a question, are these all deps that are needed?

File: src/main/app/src/Components/Landscape/Search/Search.tsx [hunk 3]
```diff
@@ -63,7 +63,7 @@ const Search: React.FC<PropsInterface> = ({locateFunction, setSidebarContent, ..
   const search = useCallback(
     (searchTerm: string, identifier: string) => {
       if (searchTerm.length < 2) return;
-
+      setHasChange(false);
```
Comment (mfbieber) [inline src/main/app/src/Components/Landscape/Search/Search.tsx:66]: Wheter it is here or after the `get()` should not really matter - does it?

File: src/main/app/src/Components/Landscape/Map/Map.tsx (hunk 2 above)
Comment (mfbieber) [reply src/main/app/src/Components/Landscape/Map/Map.tsx:191]: At least `value` is not needed in line 191.

File: src/main/app/src/Components/Landscape/Map/Map.tsx (hunk 1 above)
Comment (mfbieber) [reply src/main/app/src/Components/Landscape/Map/Map.tsx:77]: Update: the deps should be values that are used within the hook. `setValue` is not used in this hook, we can remove it.

**Review by mfbieber — COMMENTED** [review]
Focusing works ;)

File: src/main/app/src/Components/Landscape/Search/Search.tsx (hunk 3 above)
Comment (bonndan) [reply src/main/app/src/Components/Landscape/Search/Search.tsx:66]: Yes, here it prevents further requests because the ui is rendered several times before the response is available.

File: src/main/app/src/Components/Landscape/Search/Search.tsx [hunk 4]
```diff
@@ -73,20 +73,22 @@ const Search: React.FC<PropsInterface> = ({locateFunction, setSidebarContent, ..
...
-        setSidebarContent(searchResult);
-        setHasChange(false);
-      });
-    },
-    [results, setSidebarContent, locateFunction]
-  );
+        />
+    ));
+    setSidebarContent(searchResult);
+  }, [results, setSidebarContent, locateFunction]);
```
Comment (mfbieber) [inline src/main/app/src/Components/Landscape/Search/Search.tsx:91]: `setResults(result)` triggers a state change in the `Search` component and provides the new `results` to the component after a new render.

` const searchResult = results.map()` operates on the `results` available in the component. Since the new `results` are only available on the new render, we lagged behind one input character.

Now, located on an own `useEffect()`, the `searchResult` is passed on to the `setSidebarContent` function correctly, which triggers again a new render.

**Review by mfbieber — COMMENTED** [review]
I moved the `setSidebarContent()` call to an own `useEffect()`. This repairs the unecessary typing of one more character in the search field.

File: src/main/app/src/Components/Landscape/Map/Map.tsx (hunk 2 above)
Comment (bonndan) [reply src/main/app/src/Components/Landscape/Map/Map.tsx]: fixed

File: src/main/app/src/Components/Landscape/Search/Search.tsx (hunk 4 above)
Comment (bonndan) [reply src/main/app/src/Components/Landscape/Search/Search.tsx:91]: excellent 👍

File: src/main/app/src/Components/Navigation/Navigation.test.tsx [hunk 5]
```diff
@@ -6,7 +6,7 @@ import { MemoryRouter } from 'react-router-dom';
 it('should render Navigation component', () => {
   const { getByText } = render(
     <MemoryRouter>
-      <Navigation />
+      <Navigation setSidebarContent={() => {}} appBarClass={'foo'} locateFunction={() => {}} />
```
Comment (mfbieber) [inline src/main/app/src/Components/Navigation/Navigation.test.tsx:9]: 😆 I was just fixing it too!

**Review by mfbieber — COMMENTED** [review]
👍
