### PR TITLE
fix tests for windows

### LINKED ISSUE #112: Fix tests on windows
Some tests fail due to hardcoded forward slashes.

### PR DESCRIPTION
**Pull request by MarvinSchoening**
Closes #112

### CODE REVIEW

File: src/test/java/de/bonndan/nivio/input/SeedTest.java [hunk 1]
```diff
@@ -47,10 +48,18 @@ public void fails() throws MalformedURLException {
 
     @Test
     public void windowsFileLocation() throws MalformedURLException {
-        Seed seed = new Seed("c:\\a\\b\\c.yml");
+        final String separator = FileSystems.getDefault().getSeparator();
+        final String seedLocation = "c:" + separator + "a" + separator + "b" + separator+ "c.yml";
+        /*
+        TODO: Should it really be file://c/a/b/c.yml? We remove the : from C: in our Seed class but if i want to open the URL without : it wont work in my browser, but dont know whats happening internally with the URL
```
Comment (bonndan) [inline src/test/java/de/bonndan/nivio/input/SeedTest.java]: We could try to hide internals from the user, i.e. allowing anything that could be a local url, like "c:\foo\bar.yml", "./foo.yml". Given the scope of this ticket, I'd say we'd open another one to improve user experience.

File: src/test/java/de/bonndan/nivio/input/LandscapeDescriptionFactoryTest.java [hunk 2]
```diff
@@ -23,17 +24,26 @@
 
 
 class LandscapeDescriptionFactoryTest {
+    final String SEPARATOR = FileSystems.getDefault().getSeparator();
```
Comment (bonndan) [inline src/test/java/de/bonndan/nivio/input/LandscapeDescriptionFactoryTest.java]: I'd prefer to define only reusable constants here.

File: .gitignore [hunk 3]
```diff
@@ -5,3 +5,4 @@ _static
 _templates
 /.env
 *.iml
+src/test/resources/example/*_debug.png
```
Comment (bonndan) [inline .gitignore]: Sure? It might be interesting to see how code changed affect renderings, but I also see that invisible changes are annoying.

Comment (bonndan) [reply .gitignore]: agreed
